spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://id.dev.lab.dataright.io/auth/realms/deepthought/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://{{ mysql_hostname }}:3306/{{ mysql_databases[1].name }}
    username: {{ mysql_users[1].name }}
    password: {{ mysql_users[1].password }}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
