---
# tasks/main.yml
# Common configuration tasks
- name: deploy aptitude
  when: ansible_distribution == 'Ubuntu'
  package:
    name: aptitude
    state: present

- name: python pip support
  package:
    name: python3-pip

- name: deploy pymsql
  package:
    name: python3-pymysql

- name: deploy fail2ban
  include_role:
    name: manala.fail2ban
