deepthought:
  version: 1.0.0
server:
  port: 8080
  servlet:
    context-path: /cds-au
spring:
   security:
      oauth2:
         resourceserver:
            jwt:
               jwk-set-uri: https://id.dev.lab.dataright.io/auth/realms/deepthought/protocol/openid-connect/certs
   datasource:
     url: jdbc:h2:file:../localdb/deepthought;AUTO_SERVER=true
     driverClassName: org.h2.Driver
   jpa:
     open-in-view: true  
     database: H2
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
   jackson:
     default-property-inclusion: NON_EMPTY
   devtools:
     livereload:
       enabled: false

     